name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write  # required to push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      # Optional: create index.html redirect if your entry is home.html
      # (Remove this step if you already have public_html/index.html)
      - name: Ensure index.html exists (redirect to home.html if missing)
        run: |
          if [ -f public_html/home.html ] && [ ! -f public_html/index.html ]; then
            cat > public_html/index.html <<'HTML'
            <!doctype html>
            <meta charset="utf-8">
            <meta http-equiv="refresh" content="0; url=home.html">
            <link rel="canonical" href="home.html">
            HTML
          fi

      # If you have a CNAME file, place it in public_html/CNAME

      - name: Deploy public_html to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public_html
          publish_branch: gh-pages
          force_orphan: true   # clean history for Pages (optional)
          # keep_files: false  # default; set true if you want to keep old files
